name: arctic frenz
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 2,6' # At 00:00 every Tuesday and Saturday
jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Add conda to system path
        run: echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: conda env update --file environment_extraction.yml --name base
      - name: Install Chrome
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      - name: Set up Git identity
        run: |
          git config --global user.name 'davidbeard741'
          git config --global user.email 'david.beard741@gmail.com'
      - name: Pull changes from Remote
        run: git pull origin main
      - name: Run script
        run: python arctic-frenz.py
      - name: Add
        run: >
          git add
          arcticfrenz/nft_metadata_with_rarity_and_holder_data.json
          arcticfrenz/logfile.log
      - name: Commit
        run: git commit -m "Updated Arctic Frenz holders data"
      - name: Attempt Normal Push
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      - name: Force Push Changes
        run: git push --force origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: failure()
      - name: Cleanup
        run: echo "Workflow completed."
