name: by-holder
on:
  workflow_dispatch:
  schedule: 
    - cron: '30 2 * * *' # At 0200 Everyday
permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        script: [by-holder_chickentribe.py, by-holder_arctic-frenz.py]
      max-parallel: 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Add conda to system path
        run: echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: conda env update --file environment_json.yml --name base
      - name: Set up Git identity
        run: |
          git config --global user.name 'davidbeard741'
          git config --global user.email 'david.beard741@gmail.com'
      - name: Pull changes from Remote
        run: git pull origin main
      - name: Run script
        run: python ${{ matrix.script }}
      - name: Check for changes
        id: check_changes
        run: |
          git diff --quiet || echo "changes found"
          echo "changes=$?" > $GITHUB_ENV
        continue-on-error: true
      - name: Add
        if: env.changes == '1'
        run: git add arcticfrenz/by-holder.json chickentribe/by-holder.json
      - name: Commit
        if: env.changes == '1'
        run: git commit -m "Updated by-holder JSONs"
      - name: Attempt Normal Push
        if: env.changes == '1'
        id: normal_push
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      - name: Force Push Changes
        if: steps.normal_push.outcome == 'failure'
        run: git push --force origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cleanup
        run: echo "Workflow completed."