name: by-nft
on:
  workflow_dispatch:
  schedule: 
    - cron: '30 1 * * *' # At 0130 Everyday
jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Add conda to system path
        run: echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: conda env update --file environment_json.yml --name base
      - name: Set up Git identity
        run: |
          git config --global user.name 'davidbeard741'
          git config --global user.email 'david.beard741@gmail.com'
      - name: Pull changes from Remote
        run: git pull origin main
      - name: Run script for chickentribe
        run: python by-nft_chickentribe.py
      - name: Run script for arctic-frenz
        run: python by-nft_arctic-frenz.py
      - name: Add and commit
        run: |
          git add arcticfrenz/by-NFT.json chickentribe/by-NFT.json  
          git commit -m "Updated by-NFT JSONs"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          branch: main
        if: ${{ failure() }}
        run: |
          git push --force origin main
      - name: Cleanup
        run: echo "Workflow completed."
