name: charts

on:
  push:
    paths:
      - .github/workflows/charts.yml
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # At 00:00 every Sunday

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment-charts.yml --name base
    - name: Run script
      run: python histogram_chickentribe.py
    - name: Set up Git
      run: |
        git config --global user.name 'davidbeard741'
        git config --global user.email 'david.beard741@gmail.com'
    - name: Commit changes
      run: |
        git add chickentribe/histogram-ownership-duration.png
        git commit -m "Update charts"
    - name: Sync with Remote
      run: |
        git fetch
        git merge origin/main
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
