name: chickentribe

on:
  push:
    paths:
      - .github/workflows/chickentribe.yml
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    container:
      image: selenium/standalone-chrome:latest

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: pip install selenium bs4 psutil

      - name: Run script
        run: python chickentribe.py