name: chickentribe

on:
  push:
    paths:
      - .github/workflows/chickentribe.yml
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
  
      - name: Get Chrome version
        id: chrome-version
        run: |
          CHROME_VERSION=$(google-chrome --version | sed 's/Google Chrome //' | sed 's/ //g')
          echo "Extracted Chrome version: $CHROME_VERSION"
          echo "CHROME_VERSION=$CHROME_VERSION" >> $GITHUB_ENV
  
      - name: Install Chromedriver
        run: |
          CHROME_VERSION=${{ env.CHROME_VERSION }}
          echo "Using Chrome version: $CHROME_VERSION for Chromedriver"
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          echo "Chromedriver version to download: $CHROMEDRIVER_VERSION"
          curl -L -O "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          chromedriver --version

      - name: Install Python dependencies
        run: pip install selenium bs4 psutil

      - name: Run script
        run: python chickentribe.py