name: fff

on:
  push:
    paths:
      - .github/workflows/fff.yml
  workflow_dispatch:
  schedule:
    - cron: '45 */2 * * *' # every 2 hrs at the 45th min of the hr

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment_extraction.yml --name base
    - name: Install Chrome
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    - name: Run script
      run: python fff.py
    - name: Set up Git
      run: |
        git config --global user.name 'davidbeard741'
        git config --global user.email 'david.beard741@gmail.com'
    - name: Create temporary branch
      run: git checkout -b temp-branch

    - name: Commit changes excluding specific files
      run: |
        git add .
        git reset -- fff/with-rarity-and-holder-data.json fff/logfile.log
        git commit -m "Update FFF Data Excluding Specific Files"

    - name: Checkout excluded files from main branch
      run: |
        git checkout main -- fff/with-rarity-and-holder-data.json
        git checkout main -- fff/logfile.log

    - name: Force push changes to main branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        force: true

    - name: Cleanup
      run: git branch -d temp-branch
