name: Flat

on:
  push:
    paths:
      - .github/workflows/flat.yml
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * 1-5' # Run M-F at 2100UTC (1700ET)

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Fetch spy 
        uses: githubocto/flat@v3
        with:
          http_url: https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=SPY&outputsize=compact&datatype=json&apikey=SY5XUICYO3N1X8NI 
          downloaded_filename: spy-hist.json 
          postprocess: postprocessspy.js
      - name: Fetch qqq 
        uses: githubocto/flat@v3
        with:
          http_url: https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=QQQ&outputsize=compact&datatype=json&apikey=SY5XUICYO3N1X8NI 
          downloaded_filename: qqq-hist.json 
          postprocess: postprocessqqq.js
      - name: Fetch tsla 
        uses: githubocto/flat@v3
        with:
          http_url: https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=TSLA&outputsize=compact&datatype=json&apikey=SY5XUICYO3N1X8NI 
          downloaded_filename: tsla-hist.json 
          postprocess: postprocesstsla.js
      - name: Fetch nvda 
        uses: githubocto/flat@v3
        with:
          http_url: https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=NVDA&outputsize=compact&datatype=json&apikey=SY5XUICYO3N1X8NI 
          downloaded_filename: nvda-hist.json 
          postprocess: postprocessnvda.js
