name: Flat

on:
  push:
    paths:
      - .github/workflows/flat.yml
  workflow_dispatch:
  schedule:
    - cron: '0 0 31 2 *' # This time will never occcur.

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Fetch sentries 
        uses: githubocto/flat@v3
        with:
          http_url: https://api-mainnet.magiceden.dev/v2/collections/sentries/listings 
          downloaded_filename: sentries/sentries.json 
          postprocess: sentries/postprocesssentries.js
