name: histogram
on:
  workflow_dispatch: 
  schedule: 
    - cron: '30 5 * * 1,2,3,4,5,6,0' # At 0530 on everyday
jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda env update --file environment_charts.yml --name base
      - name: Run script
        run: python histogram_chickentribe.py
      - name: Run script
        run: python histogram_arctic-frenz.py
      - name: Stash changes
        run: |
          for file in chickentribe/histogram.png arcticfrenz/histogram.png; do
            if git diff --exit-code --quiet "$file"; then
              echo "$file no changes to commit, skipping."
            else
              git stash push -u "$file"
            fi
          done
      - name: Set up Git
        run: |
          git config --global user.name 'davidbeard741'
          git config --global user.email 'david.beard741@gmail.com'
      - name: Sync with Remote
        run: |
          git fetch
          git rebase origin/main
      - name: Check and apply stash
        run: >
          for file in chickentribe/histogram.png
          arcticfrenz/histogram.png; do
            if git stash list | grep -q "$file"; then
              git stash apply "$file"
              echo "Applied stash for $file"
            else
              echo "No stash found for $file, skipping"
            fi
          done
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          branch: main
      - name: Remove Stash
        run: |
          git stash drop
