name: log-delete

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *' # 08:00 UTC daily

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Git
      run: |
        git config --global user.name 'davidbeard741'
        git config --global user.email 'david.beard741@gmail.com'
    - name: Commit changes
      run: |
        for file in fff/logfile.log smb/logfile.log solc/logfile.log okay-bears/logfile.log quekz/logfile.log chickentribe/logfile.log arcticfrenz/logfile.log sentries/logfile.log madlads/logfile.log claynosaurz/logfile.log; do
          if [ -f "$file" ]; then
            git rm "$file"
          else
            echo "$file does not exist, skipping."
          fi
        done
        git commit -m "Remove Log Files" || echo "No changes to commit"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
