name: log-reduce

on:
  workflow_dispatch:
  schedule:
    - cron: '55 8 * * *'
permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Git
      run: |
        git config --global user.name 'davidbeard741'
        git config --global user.email 'david.beard741@gmail.com'
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PAT }}
    - name: Reduce Log File Size
      run: |
        max_size=500  # maximum size in lines
        for file in fff/logfile.log smb/logfile.log solc/logfile.log okay-bears/logfile.log quekz/logfile.log chickentribe/logfile.log arcticfrenz/logfile.log sentries/logfile.log madlads/logfile.log claynosaurz/logfile.log; do
          if [ -f "$file" ]; then
            # Keep only the last max_size lines of the file
            tail -n $max_size "$file" > temp.log
            mv temp.log "$file"
            git add "$file"
          else
            echo "$file does not exist, skipping."
          fi
        done
    - name: Stash Changes
      run: git stash --include-untracked
    - name: Pull changes from Remote
      run: git pull --rebase origin main
    - name: Reapply Stashed Changes
      run: git stash pop
    - name: Commit
      run: git commit -m "Reduce Log Files Size" || echo "No changes to commit"
    - name: Attempt Normal Push
      id: normal_push
      run: git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PAT }}
      continue-on-error: true
    - name: Force Push Changes
      if: steps.normal_push.outcome == 'failure'
      run: git push --force origin main
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PAT }}
    - name: Cleanup
      run: echo "Workflow completed."
