name: okay-bears

on:
  push:
    paths:
      - .github/workflows/okay-bears.yml
  workflow_dispatch:
  schedule:
    - cron: '30 */2 * * *' # every 2 hrs at the 30th min of the hr

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment_extraction.yml --name base
    - name: Install Chrome
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    - name: Run script
      run: python okay-bears.py
    - name: Set up Git
      run: |
        git config --global user.name 'davidbeard741'
        git config --global user.email 'david.beard741@gmail.com'
    - name: Commit changes
      run: |
        git add okay-bears/with-rarity-and-holder-data.json okay-bears/logfile.log
        git commit -m "Update Quekz Holder Data and Log"
    - name: Sync with Remote
      run: |
        git fetch
        git merge origin/main
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
