name: rank-holders

on:
  push:
    paths:
      - .github/workflows/rank-holders.yml
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * 1,3,5,0' # At 0330 on every Mon, Wed, Fri, and Sun

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment_json.yml --name base
    - name: Run script
      run: python rank-holders_chickentribe.py
    - name: Run script
      run: python rank-holders_arctic-frenz.py
    - name: Set up Git
      run: |
        git config --global user.name 'davidbeard741'
        git config --global user.email 'david.beard741@gmail.com'
    - name: Commit changes
      run: |
        for file in chickentribe/ranked-holders.json arcticfrenz/ranked-holders.json; do
          if git diff --exit-code --quiet "$file"; then
            echo "$file no changes to commit, skipping."
          else
            git add "$file"
            git commit -m "Update $file"
          fi
        done
    - name: Sync with Remote
      run: |
        git fetch
        git rebase origin/main
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
