name: Slat

on:
  push:
    paths:
      - .github/workflows/slat.yml
  workflow_dispatch:
  schedule:
    - cron: '0 0 31 2 *' # This time will never occcur, temp disabling the job until we find another api source.