name: smb
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *' # every 2 hrs at the top of the hr
jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Add conda to system path
        run: echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: conda env update --file environment_extraction.yml --name base
      - name: Install Chrome
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      - name: Set up Git identity
        run: |
          git config --global user.name 'davidbeard741'
          git config --global user.email 'david.beard741@gmail.com'
      - name: Run script
        run: python smb.py
      - name: Stash specific local changes
        run: git stash push -m "Local changes" -- smb/with-rarity-and-holder-data.json smb/logfile.log
      - name: Pull changes from Remote
        run: git pull origin main
      - name: Apply stashed changes
        run: git stash pop || true
      - name: Add and commit work brought back from stash
        run: |
          git add smb/with-rarity-and-holder-data.json smb/logfile.log
          git commit -m "Updated data"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          branch: main
      - name: Cleanup
        run: echo "Workflow completed."
