name: solc
on:
  workflow_dispatch:
  schedule:
    - cron: '15 */2 * * *' # every 2 hrs at the 15th min of the hr
jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Add conda to system path
        run: echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: conda env update --file environment_extraction.yml --name base
      - name: Install Chrome
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      - name: Set up Git identity
        run: |
          git config --global user.name 'davidbeard741'
          git config --global user.email 'david.beard741@gmail.com'
      - name: Run script and stage changes
        run: |
          python solc.py
          git add solc/with-rarity-and-holder-data.json solc/logfile.log
      - name: Commit changes
        run: git commit -m "Updated SOLC data"
      - name: Sync with Remote
        run: |
          git fetch
          git rebase origin/main
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          branch: main
      - name: Cleanup
        run: echo "Workflow completed."